### ISSUE TITLE
crash: TypeError: Cannot read property 'pushMessage' of undefined

### ISSUE THREAD

**Issue by Picktrick** [thelounge/thelounge#2096]
I have thelounge `v2.7.0 (Node.js 9.5.0 on Debian 9 x64)` being crashed several times per day with a following error:

```
/usr/lib/node_modules/thelounge/src/plugins/irc-events/banlist.js:18
                        network.getChannel(channel).pushMessage(client, msg, true);
                                                   ^

TypeError: Cannot read property 'pushMessage' of undefined
    at IrcClient.<anonymous> (/usr/lib/node_modules/thelounge/src/plugins/irc-events/banlist.js:18:31)
    at IrcClient.emit (/usr/lib/node_modules/thelounge/node_modules/eventemitter3/index.js:150:33)
    at /usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:188:20
    at next (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:64:3)
    at IrcCommandHandler.<anonymous> (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:182:34)
    at IrcCommandHandler.emit (/usr/lib/node_modules/thelounge/node_modules/eventemitter3/index.js:130:35)
    at IrcCommandHandler.emit (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/commands/handler.js:97:23)
    at IrcCommandHandler.RPL_ENDOFBANLIST (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/commands/handlers/channel.js:102:14)
    at IrcCommandHandler.executeCommand (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/commands/handler.js:64:37)

```

The instance is being used by 50+ users at once and there are no more specific messages or errors.

I personally can't reproduce the problem by myself, but would like to know how to turn on debugging specific to this situation in order to provide more details.

**Comment by xPaw** [comment]
That's fixed in master by 3074251be9677198c9aa7122e6690c8d060a3da6.
