### ISSUE TITLE
chmod prevents use of thelounge in OpenShift

### ISSUE THREAD

**Issue by brianclemens** [thelounge/thelounge#2656]
Attempting to spin up any version of thelounge in OpenShift results in the following error:
```
fs.js:1123
  return binding.chmod(pathModule._makeLong(path), modeNum(mode));
                 ^

Error: EPERM: operation not permitted, chmod '/var/opt/thelounge'
    at Object.fs.chmodSync (fs.js:1123:18)
    at initalizeConfig (/usr/local/lib/node_modules/thelounge/src/command-line/start.js:26:6)
    at Command.<anonymous> (/usr/local/lib/node_modules/thelounge/src/command-line/start.js:17:3)
    at Command.listener (/usr/local/lib/node_modules/thelounge/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/thelounge/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/thelounge/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/thelounge/src/command-line/index.js:58:9)
at Module._compile (module.js:652:30)
```

**Comment by xPaw** [comment]
It's called here:
https://github.com/thelounge/thelounge/blob/061fa615cea3297d97daf7d3054933d741c2b302/src/command-line/start.js#L26

Why does openshift prevent chmod? Is it a permission issue that you could fix on your end?

**Comment by crobby** [comment]
I suspect that the "don't run as root" policy in openshift is causing the issue here.  I'd bet that running the following on your openshift cluster (from admin) will get it working.  Warning though, this will allow containers to run as "anyuid", which includes root (root seems to be necessary for this container to run).
`oadm policy add-scc-to-group anyuid system:authenticated`
The above lets any authenticated user run containers as any uid (including root)

**Comment by xPaw** [comment]
`chmod` doesn't need root if you own the folder (in this case it does, as chmod is only attempted after its been created).

**Comment by crobby** [comment]
I just tried this out and I tweaked the docker-entrypoint.sh to do an ls -l /var/opt/thelounge and for me it showed up as a root-owned folder.

**Comment by xPaw** [comment]
Which `docker-entrypoint.sh`? As of v3 our docker container drops root permissions https://github.com/thelounge/thelounge-docker#executing-commands-in-the-container

**Comment by crobby** [comment]
The one I tweaked is:  https://github.com/thelounge/thelounge-docker/blob/master/docker-entrypoint.sh

**Comment by xPaw** [comment]
Was it `node:root` or `root:root`?

**Comment by crobby** [comment]
Hmm, fair question.  I don't have it in front of me at the moment since I eventually fixed my problem.  I recall seeing root, but I don't recall seeing node in the listing.  Sorry that wasn't very specific.  I'll see if I can recreate the original problem on a test cluster.

**Comment by xPaw** [comment]
Either way, this still sounds like a problem with openshift.

**Comment by crobby** [comment]
Sure, it's purely an openshift-related issue due to the security model there.  I posted my original note only as a breadcrumb for any other openshift users that might stumble on this issue.  I'm not advocating for any particular fix here.

**Comment by xPaw** [comment]
I'm gonna close this issue then.

**Comment by blinkiz** [comment]
This is still an issue in OpenShift 4.9.
Storage provider like NFS do not allow you to change permissions on the created volume root like `/config`. You are allowed to change permission on anything below it like `/config/*`.

```bash
# Correct way
[userX@utils] chmod --changes --recursive 700 config/*
mode of 'config/config.js' changed from 0644 (rw-r--r--) to 0700 (rwx------)
mode of 'config/packages' changed from 0755 (rwxr-xr-x) to 0700 (rwx------)
mode of 'config/users' changed from 0755 (rwxr-xr-x) to 0700 (rwx------)

# Incorrect way
[userX@utils] chmod --changes --recursive 700 config/
chmod: changing permissions of 'config/': Operation not permitted
```

Inside the pod, this looks like
```
internal/fs/utils.js:269
    throw err;
    ^

Error: EPERM: operation not permitted, chmod '/config'
    at Object.chmodSync (fs.js:1205:3)
    at initalizeConfig (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/command-line/start.js:26:6)
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/command-line/start.js:17:3)
    at Command.listener [as _actionHandler] (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:422:31)
    at Command._parseCommand (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:975:14)
    at Command._dispatchSubcommand (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:926:18)
    at Command._parseCommand (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:943:12)
    at Command.parse (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:778:10)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/command-line/index.js:56:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  errno: -1,
  syscall: 'chmod',
  code: 'EPERM',
  path: '/config'
}
```

**Comment by brunnre8** [comment]
>Storage provider like NFS do not allow you to change permissions on the created volume root

Give it a subfolder then, which TL actually has full permissions on.

**Comment by blinkiz** [comment]
> Give it a subfolder then, which TL actually has full permissions on.

Of course, setting THELOUNGE_HOME to `/config/thelounge` works perfectly.
