### ISSUE TITLE
TheLounge bricked after attempting to join a PSYC network

### ISSUE THREAD

**Issue by Nuc1eoN** [thelounge/thelounge#4246]
I have tried to join `irc://psyced.org/welcome` and apparently it broke my install of TheLougne. Not sure what to do now.

It happened only after I checked "Connect securely over TLS" (or something like that).

I would share start up logs but I am using thelounge over a systemd service which starts a podman container (yeah super advanced) and `systemctl status container-thelounge.service` has nothing useful what so ever, apart from that it failed with "exit-code".

So probably how to reproduce this:
1. Open `irc://psyced.org/welcome` with thelougne
2. Select TLS connection check mark and then connect
3. Enjoy downtime

**Comment by brunnre8** [comment]
```
/usr/lib/thelounge/node_modules/thelounge/src/plugins/irc-events/connection.js:202
                data.options.PREFIX.forEach((mode) => {
                                    ^
TypeError: data.options.PREFIX.forEach is not a function
    at IrcClient.<anonymous> (/usr/lib/thelounge/node_modules/thelounge/src/plugins/irc-events/connection.js:202:23)
    at IrcClient.emit (/usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/node_modules/eventemitter3/index.js:18  1:35)
    at /usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/src/client.js:223:24
    at next (/usr/lib/thelounge/node_modules/thelounge/node_modules/middleware-handler/index.js:42:18)
    at MiddlewareHandler.handle (/usr/lib/thelounge/node_modules/thelounge/node_modules/middleware-handler/index.js:64:3)
    at IrcCommandHandler.<anonymous> (/usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/src/client.js:217:38)
    at IrcCommandHandler.emit (/usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/node_modules/eventemitter3/ind  ex.js:182:35)
    at IrcCommandHandler.emit (/usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/src/commands/handler.js:90:27)
    at Array.RPL_ISUPPORT (/usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/src/commands/handlers/registration  .js:84:17)
    at IrcCommandHandler.executeCommand (/usr/lib/thelounge/node_modules/thelounge/node_modules/irc-framework/src/commands/handler  .js:64:40)

```

**Comment by brunnre8** [comment]
data that leads to the crash:
```js
{
    options: {
    CASEMAPPING: 'ascii',
    PREFIX: '',
    PSYC: '.99',
    ALIAS: true,
    AVAILABILITY: true,
    FRIEND: true,
    HISTORY: true,
    MOOD: true,
    SHOUT: true,
    SSET: true,
    STATUS: true,
    SUBSCRIBE: true,
    THREAD: true,
    TRUST: true,
    CHANTYPES: [ '#' ],
    CHANMODES: [ '' ],
    NICKLEN: '256',
    CHANNELLEN: '256',
    TOPICLEN: '444',
    KICKLEN: '444',
    AWAYLEN: '444',
    MAXTARGETS: '1',
    CHARSET: 'UTF-8',
    NETWORK: 'psyced.org',
    CTCP: 'PRESENCE,TS',
    UNIFORMS: 'psyc,xmpp',
    'ARE SUPPORTED BY THIS SERVER': true
  },
  cap: [],
  tags: {}
}
```
PR opened upstream: https://github.com/kiwiirc/irc-framework/pull/284

**Comment by Nuc1eoN** [comment]
Thanks! When can I expect this bugfix to be available in thelounge?

Or maybe can I easily fix this for myself for the time being? Thanks in advance.

**Comment by brunnre8** [comment]
when we get a release in the upstream lib which should be pretty soon.

As for easily applying it, you need to build thelounge locally with a non released irc-framework, which isn't hard to do but requires at least some knowledge of the js ecosystem (or willingness to learn)

**Comment by Nuc1eoN** [comment]
Ok I am gonna wait then :)

**Comment by brunnre8** [comment]
Fixed on master, should be included in the next release. For now you can run the latest and greatest if you install it via yarn.
