### ISSUE TITLE
reverse DNS lookup failure crashes TL

### ISSUE THREAD

**Issue by dr460nf1r3** [thelounge/thelounge#4768]
Hello! Thelounge likes to crash whenever it loads as of late.
The instance can be found [here](https://irc.garudalinux.org/#/), logs are available below:
 
```
2023-07-30 12:39:28 [INFO] The Lounge v4.4.1 (Node.js 18.17.0 on linux x64)
2023-07-30 12:39:28 [INFO] Configuration file: /var/opt/thelounge/config.js
2023-07-30 12:39:28 [INFO] Available at http://[::]:9000/ in public mode
2023-07-30 12:39:28 [INFO] Package thelounge-theme-dracula v1.1.1 loaded
node:internal/dns/callback_resolver:74
if (err) throw dnsException(err, bindingName, name);
^
Error: getHostByAddr EINVAL 2a02:3035:412:460b:5ace:a39c:d0ee:dfa8
at ResolverBase.getHostByAddr (node:internal/dns/callback_resolver:74:20)
at reverseDnsLookup (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/server.js:777:19)
at initClient (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/server.js:724:9)
at Socket.performAuthentication (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/server.js:737:9)
at Namespace.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/thelounge/dist/server/server.js:182:39)
at Namespace.emit (node:events:514:28)
at Namespace.emitReserved (/usr/local/share/.config/yarn/global/node_modules/socket.io/dist/typed-events.js:56:22)
at Namespace._doConnect (/usr/local/share/.config/yarn/global/node_modules/socket.io/dist/namespace.js:268:14)
at /usr/local/share/.config/yarn/global/node_modules/socket.io/dist/namespace.js:231:22
at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
errno: -22,
code: 'EINVAL',
syscall: 'getHostByAddr',
hostname: '2a02:3035:412:460b:5ace:a39c:d0ee:dfa8'
}
Node.js v18.17.0
```

A very similar issue can be found here, which was apparenly solved though: https://github.com/thelounge/thelounge/issues/352.

**Comment by brunnre8** [comment]
I doubt the linked issue has any significance here... completely different error.

It's rather a case of https://github.com/nodejs/node/issues/3112 should be relatively easy to work around if you fancy sending a patch our way.

I've removed the docker mention as it has no relevance here, this is an issue with the code and not the deployment

**Comment by dr460nf1r3** [comment]
Oh, I thought I might mention it. I don't think I'm skilled enough in Javascript to actually contribute the fix :/

**Comment by d3xt3r01** [comment]
This started happenning to me recently too

```
node:internal/dns/callback_resolver:74
    if (err) throw dnsException(err, bindingName, name);
             ^

Error: getHostByAddr EINVAL 2001:67c:6ec:203:192:42:116:196
    at ResolverBase.getHostByAddr (node:internal/dns/callback_resolver:74:20)
    at reverseDnsLookup (/home/ircd/src/thelounge/dist/server/server.js:777:19)
    at initClient (/home/ircd/src/thelounge/dist/server/server.js:724:9)
    at Socket.performAuthentication (/home/ircd/src/thelounge/dist/server/server.js:737:9)
    at Namespace.<anonymous> (/home/ircd/src/thelounge/dist/server/server.js:182:39)
    at Namespace.emit (node:events:514:28)
    at Namespace.emitReserved (/home/ircd/src/thelounge/node_modules/socket.io/dist/typed-events.js:56:22)
    at Namespace._doConnect (/home/ircd/src/thelounge/node_modules/socket.io/dist/namespace.js:268:14)
    at /home/ircd/src/thelounge/node_modules/socket.io/dist/namespace.js:231:22
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'getHostByAddr',
  hostname: '2001:67c:6ec:203:192:42:116:196'
}

Node.js v18.17.1
error Command failed with exit code 1.
```
