### ISSUE TITLE
From a clean install

### ISSUE THREAD

**Issue by blixten85** [thelounge/thelounge#4913]
This is from a fresh install of the lounge in a docker container. 
I don't know what's wrong with it, the lounge worked when i ran LibreELEC.

```
Node.js v20.15.1
2024-09-15 03:30:25 [INFO] The Lounge v4.4.3 (Node.js 20.15.1 on linux arm64)
2024-09-15 03:30:25 [INFO] Configuration file: /config/config.js
2024-09-15 03:30:25 [INFO] Available at http://[::]:9000/ in private mode
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new WebPush (/app/thelounge/dist/server/plugins/webpush.js:56:37)
    at ClientManager.init (/app/thelounge/dist/server/clientManager.js:27:24)
    at suicideTimeout (/app/thelounge/dist/server/server.js:208:21)
    at new Identification (/app/thelounge/dist/server/identification.js:47:13)
    at Server.<anonymous> (/app/thelounge/dist/server/server.js:199:9)
    at Object.onceWrapper (node:events:633:28)
    at Server.emit (node:events:531:35)
    at emitListeningNT (node:net:1932:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v20.15.1
2024-09-15 03:30:27 [INFO] The Lounge v4.4.3 (Node.js 20.15.1 on linux arm64)
2024-09-15 03:30:27 [INFO] Configuration file: /config/config.js
2024-09-15 03:30:27 [INFO] Available at http://[::]:9000/ in private mode
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new WebPush (/app/thelounge/dist/server/plugins/webpush.js:56:37)
    at ClientManager.init (/app/thelounge/dist/server/clientManager.js:27:24)
    at suicideTimeout (/app/thelounge/dist/server/server.js:208:21)
    at new Identification (/app/thelounge/dist/server/identification.js:47:13)
    at Server.<anonymous> (/app/thelounge/dist/server/server.js:199:9)
    at Object.onceWrapper (node:events:633:28)
    at Server.emit (node:events:531:35)
    at emitListeningNT (node:net:1932:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Comment by brunnre8** [comment]
this is an issue tracker for developers and not a support forum, head over to our IRC chan #thelounge on libera
